/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import {BytesLike} from "@ethersproject/bytes";
import {Listener, Provider} from "@ethersproject/providers";
import {FunctionFragment, EventFragment, Result} from "@ethersproject/abi";
import type {TypedEventFilter, TypedEvent, TypedListener} from "./common";

interface MelandTierStorageInterface extends ethers.utils.Interface {
  functions: {
    "addOptionReward(uint256,tuple[],tuple[],tuple[])": FunctionFragment;
    "add100PercentReward(uint256,tuple[],tuple[],tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addOptionReward",
    values: [
      BigNumberish,
      {erc1155: string; tokenIds: BigNumberish[]; amounts: BigNumberish[]}[],
      {erc721: string; tokenId: BigNumberish}[],
      {erc20: string; amount: BigNumberish}[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "add100PercentReward",
    values: [
      BigNumberish,
      {erc1155: string; tokenIds: BigNumberish[]; amounts: BigNumberish[]}[],
      {erc721: string; tokenId: BigNumberish}[],
      {erc20: string; amount: BigNumberish}[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOptionReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add100PercentReward",
    data: BytesLike
  ): Result;

  events: {
    "RewaardPoolUpdate(uint256)": EventFragment;
    "TierStartSale(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RewaardPoolUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TierStartSale"): EventFragment;
}

export type RewaardPoolUpdateEvent = TypedEvent<[BigNumber] & {cid: BigNumber}>;

export type TierStartSaleEvent = TypedEvent<[BigNumber] & {cid: BigNumber}>;

export class MelandTierStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MelandTierStorageInterface;

  functions: {
    addOptionReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<ContractTransaction>;

    add100PercentReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<ContractTransaction>;
  };

  addOptionReward(
    cid: BigNumberish,
    erc1155rewards: {
      erc1155: string;
      tokenIds: BigNumberish[];
      amounts: BigNumberish[];
    }[],
    erc721rewards: {erc721: string; tokenId: BigNumberish}[],
    erc20rewards: {erc20: string; amount: BigNumberish}[],
    overrides?: Overrides & {from?: string | Promise<string>}
  ): Promise<ContractTransaction>;

  add100PercentReward(
    cid: BigNumberish,
    erc1155rewards: {
      erc1155: string;
      tokenIds: BigNumberish[];
      amounts: BigNumberish[];
    }[],
    erc721rewards: {erc721: string; tokenId: BigNumberish}[],
    erc20rewards: {erc20: string; amount: BigNumberish}[],
    overrides?: Overrides & {from?: string | Promise<string>}
  ): Promise<ContractTransaction>;

  callStatic: {
    addOptionReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: CallOverrides
    ): Promise<void>;

    add100PercentReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RewaardPoolUpdate(uint256)"(
      cid?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], {cid: BigNumber}>;

    RewaardPoolUpdate(
      cid?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], {cid: BigNumber}>;

    "TierStartSale(uint256)"(
      cid?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], {cid: BigNumber}>;

    TierStartSale(
      cid?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], {cid: BigNumber}>;
  };

  estimateGas: {
    addOptionReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<BigNumber>;

    add100PercentReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addOptionReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<PopulatedTransaction>;

    add100PercentReward(
      cid: BigNumberish,
      erc1155rewards: {
        erc1155: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
      }[],
      erc721rewards: {erc721: string; tokenId: BigNumberish}[],
      erc20rewards: {erc20: string; amount: BigNumberish}[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<PopulatedTransaction>;
  };
}
